Ongoing pylint improvements
drauger-os-development/system-installer pull request #68
Opened 2022-02-04 00:53 UTC by SenlisO

This pull request represents ongoing pylint improvements.  I'll let you know when a larger block of code is ready for the pull request to be accepted, but it can be pulled in at any time.

2022-02-04 00:53 UTC, pep8speaks commented
Hello @SenlisO! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`usr/share/system-installer/UI/main.py`](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py):

> [Line 38:1](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L38): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 64:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 66:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L66): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 115:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L115): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 125:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L125): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 128:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L128): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 131:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L131): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 158:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L158): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 471:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L471): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 512:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L512): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 552:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L552): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 553:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L553): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 579:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L579): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 662:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L662): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 678:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L678): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 710:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L710): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 719:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L719): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 793:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L793): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 800:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L800): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 806:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L806): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 816:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L816): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 839:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L839): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 860:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L860): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 907:75](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L907): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 908:45](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L908): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 908:72](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L908): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 909:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L909): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 976:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L976): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 978:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L978): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 985:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L985): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 987:80](https://github.com/drauger-os-development/system-installer/blob/5fe044d3bf1fb1c3a7b6780d4618bb8be5efc16a/usr/share/system-installer/UI/main.py#L987): [E501](https://duckduckgo.com/?q=pep8% [...]

2022-02-04 01:06 UTC, Batcastle reviewed
Just a quick question regarding a block of unusual looking code.

2022-02-04 01:06 UTC, Batcastle commented on usr/share/system-installer/UI/main.py
> +                                            "{int(auto_partitioner.bytes_to_gb(each1['size']))}GB")
Does this block of code actually work? If so and pylint doesn't complain then that's fine. Just looks more like shell code than Python.

2022-02-04 01:19 UTC, Batcastle requested changes
A lot of these functions have extra arguments because GTK passes the widget that called the function to the function itself. Without that extra argument it can throw errors, crashing `system-installer`. Please be sure, when working in classes in UI files, that arguments for functions are not needed during run time.

2022-02-04 10:13 UTC, SenlisO commented on usr/share/system-installer/UI/main.py
> +                                            "{int(auto_partitioner.bytes_to_gb(each1['size']))}GB")
When I looked up how to split strings to multiple lines, this was the protocol.  Also, it made pylint happy.  I still need to test it though.

2022-02-04 10:16 UTC, SenlisO commented
> A lot of these functions have extra arguments because GTK passes the widget that called the function to the function itself. Without that extra argument it can throw errors, crashing `system-installer`. Please be sure, when working in classes in UI files, that arguments for functions are not needed during run time.

I take it you are referring to the functions that include things like "button" as a param but it isn't used anywhere in the function itself.  In that case, I can add all of those back, add a flag so that pylint ignores it, and then put in docstrings that explain that those params belong there.

2022-02-14 14:07 UTC, SenlisO commented
I added the params back and added a flag and a comment to ignore unused-params for those functions that need them for GTK

2022-03-13 20:11 UTC, closed without merging